language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:  
  - LARAVEL_VERSION=5.*  
  - LARAVEL_VERSION=6.*

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;  
  - composer update

script:
  - composer require alaaelgndy/file-uploader
  - php artisan migrate