language: php

php:
  - '7.2'

env:  
  # - LARAVEL_VERSION=5.6.*  
  # - LARAVEL_VERSION=5.7.*  
  # - LARAVEL_VERSION=5.8.*  
  - LARAVEL_VERSION=6.*

services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - if [ "$LARAVEL_VERSION" != "" ]; then composer create-project --prefer-dist laravel/laravel ${LARAVEL_VERSION} ${LARAVEL_VERSION}; fi;
  - travis_retry composer self-update
  - sudo mysql -e 'create database uploader;'

script:
  - cd ${LARAVEL_VERSION}
  - cp ../.env.travis .env
  - composer require alaaelgndy/file-uploader:dev-$TRAVIS_PULL_REQUEST_BRANCH
  - php artisan key:generate
  - php artisan migrate
  - ./vendor/bin/phpunit vendor/alaaelgndy/file-uploader/src/tests/Unit/.