language: php

php:
  - '7.3'

services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - composer create-project --prefer-dist laravel/laravel blog "6.*" --dev
  - sudo mysql -e 'create database uploader;'

script:
  - cd blog
  - cp ../.env.travis .env
  - composer require alaaelgndy/file-uploader
  - php artisan key:generate
  - php artisan migrate
  - ./vendor/bin/phpunit vendor/alaaelgndy/file-uploader/src/tests/Unit/*