language: php

php:
  - '7.3'

services:
  - mysql

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - composer create-project --prefer-dist laravel/laravel blog "6.*" --dev

script:
  - cd blog
  - composer require alaaelgndy/file-uploader
  - php artisan migrate